/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface IEcdsaOwnershipRegistryModuleInterface
  extends utils.Interface {
  functions: {
    "getOwner(address)": FunctionFragment;
    "initForSmartAccount(address)": FunctionFragment;
    "isValidSignatureForAddress(bytes32,bytes,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getOwner"
      | "initForSmartAccount"
      | "isValidSignatureForAddress"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initForSmartAccount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignatureForAddress",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initForSmartAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignatureForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  smartAccount: string;
  oldOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface IEcdsaOwnershipRegistryModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IEcdsaOwnershipRegistryModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getOwner(
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initForSmartAccount(
      eoaOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    isValidSignatureForAddress(
      dataHash: BytesLike,
      moduleSignature: BytesLike,
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    transferOwnership(
      owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  getOwner(smartAccount: string, overrides?: CallOverrides): Promise<string>;

  initForSmartAccount(
    eoaOwner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  isValidSignatureForAddress(
    dataHash: BytesLike,
    moduleSignature: BytesLike,
    smartAccount: string,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  transferOwnership(
    owner: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    getOwner(smartAccount: string, overrides?: CallOverrides): Promise<string>;

    initForSmartAccount(
      eoaOwner: string,
      overrides?: CallOverrides
    ): Promise<string>;

    isValidSignatureForAddress(
      dataHash: BytesLike,
      moduleSignature: BytesLike,
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(owner: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address,address)"(
      smartAccount?: string | null,
      oldOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      smartAccount?: string | null,
      oldOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    getOwner(
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initForSmartAccount(
      eoaOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    isValidSignatureForAddress(
      dataHash: BytesLike,
      moduleSignature: BytesLike,
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    transferOwnership(
      owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getOwner(
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initForSmartAccount(
      eoaOwner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    isValidSignatureForAddress(
      dataHash: BytesLike,
      moduleSignature: BytesLike,
      smartAccount: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      owner: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
