/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEcdsaOwnershipRegistryModule,
  IEcdsaOwnershipRegistryModuleInterface,
} from "../IEcdsaOwnershipRegistryModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
    ],
    name: "AlreadyInitedForSmartAccount",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
    ],
    name: "NoOwnerRegisteredForSmartAccount",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "NotEOA",
    type: "error",
  },
  {
    inputs: [],
    name: "WrongSignatureLength",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddressNotAllowedAsOwner",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
    ],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "eoaOwner",
        type: "address",
      },
    ],
    name: "initForSmartAccount",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "moduleSignature",
        type: "bytes",
      },
      {
        internalType: "address",
        name: "smartAccount",
        type: "address",
      },
    ],
    name: "isValidSignatureForAddress",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEcdsaOwnershipRegistryModule__factory {
  static readonly abi = _abi;
  static createInterface(): IEcdsaOwnershipRegistryModuleInterface {
    return new utils.Interface(_abi) as IEcdsaOwnershipRegistryModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEcdsaOwnershipRegistryModule {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IEcdsaOwnershipRegistryModule;
  }
}
